### PR TITLE
Fix comments

### PR DESCRIPTION
**Pull request by bnainar**

### CODE REVIEW

**Comment by bnainar** [comment]
Done 😁

**Comment by spikecodes** [comment]
Thanks! :)

**Comment by bnainar** [comment]
@spikecodes, I only changed .GitHub folder, then how did GitHub Actions failed. Pls look into that

**Comment by spikecodes** [comment]
GitHub Actions fails for any PRs here because the Docker Build requires a Secret that only gets pushed to the Action when I initiate the a runner.

**Pull request merged**
