### PR TITLE
Subscribing to subreddits (favorites)

### PR DESCRIPTION
**Pull request by mcrossman**
Implements basic subreddit subscriptions/favourites (#23), managed through each sub's sidebar.

I've never written in Rust before so the code is pretty rough.

### Changes in code/Implementation details

- Subscription list is a comma-separated list of subreddit names, saved under the `subscriptions` cookie.
- Adding a sub to the list requires clicking the "subscribe" button in the sidebar
  - Subscribe is a GET request to `/r/{{ subreddit }}/subscribe/`, which will add that sub to the cookie
- Removing a sub requires clicking "unsubscribe" in the sidebar or in settings
  - Unsubscribe is a GET request to `/r/{{ subreddit }}/unsubscribe/` which will remove that sub from the `subscriptions` cookie or delete the cookie if it's the last one
  - GET is used instead of POST because I ran into strange behaviour when trying to loop over the unsubscribe forms in settings. It seems looping with forms results in the first form tag being ignored.

### Visual changes

- A new subscriptions dropdown (uses `details` now but I might test hover in the future)
  - If you've subscribed to a subreddit, it will appear
  - It's a vertical list similar in appearance to the sort bar
  - The active subreddit is highlighted in the accent colour
- Margins in the `main` element have been reduced to allow for an element to fit in above. The navbar padding has become `body` padding.
- Other elements near the subscriptions dropdown have had their styles tweaked.

### Sub list considerations

~~The sub list currently appears as an extra horizontal bar (in the style of the sort bar) under the navbar.~~

The sub list was previously a horizontal bar. Now it's a drop-down button that should stay at the top left of the main content or be centred under the nav bar on mobile.

If we place it inside the navbar, it makes it way too tall, especially on mobile. Other sub lists like on RES or teddit are part of the navbar but those bars aren't fixed.

~~Another idea is to use a dropdown menu for a vertical list like new Reddit.~~

Reddit has a drop-down button in the navbar, but it was a bit messy trying to fit the button (& a smaller symbol variant) with everything else in the mobile navbar.

### CODE REVIEW

**Comment by mcrossman** [comment]
Changed the sub list to be a dropdown more in line with new Reddit's vertical list.

libreddit-subs

**Comment by robrobinbin** [comment]
Wow, very cool stuff and seems to work well!

The alignment looks a bit off on front page though ;)
image

**Comment by robrobinbin** [comment]
The following is not a direct feedback on your PR or request to you, but rather just me brainstorming out loud about possible future iterations of this :smile:

I've had look at how the new reddit handles this currently and made the following mock up.

The idea would be to add a cog and info icon to settings and about, respectively, and hide the labels on mobile.

image

**Comment by mcrossman** [comment]
> The alignment looks a bit off on front page though ;)

The way I've been aligning the button is a real mess.

> I've had look at how the new reddit handles this currently and made the following mock up.

On mobile, I'm thinking about hiding the logo and having three buttons above the search bar. Though it might be better to hide the search bar under a search button just like the sub list.

**Comment by mcrossman** [comment]
Moved the sub list back into the navbar. 

I think an about page might be more appropriate in a future PR. This one's already getting quite large.

**Comment by spikecodes** [comment]
Fantastic PR! Thanks! I'm able to subscribe successfully but I cannot unsubscribe for some reason. Are you able to reproduce this?

**Comment by mcrossman** [comment]
> Fantastic PR! Thanks! I'm able to subscribe successfully but I cannot unsubscribe for some reason. Are you able to reproduce this issue?

Yes. This happens when you're only subscribed to one subreddit. I'm looking into it.

**Comment by mcrossman** [comment]
```rust
if sub_list.is_empty() {
  res.del_cookie(&Cookie::named("subscriptions"));
  // cookie still exists after this
}
```

It seems that deleting a cookie in this way (which is based on `settings.rs`) doesn't seem to work. I feel like I'm missing a method.

The quick workaround is to get rid of the if statement and let it set an empty cookie.

**Comment by spikecodes** [comment]
I'm not sure why the that method isn't working yet it works in settings. I also found that when unsubscribing from a subreddit, it sets the entire `subscriptions` cookie blank.
image

I will do some testing.

**Comment by spikecodes** [comment]
An alternative for now would be setting the cookie, but simply making it's value blank. This isn't ideal (still takes up a cookie on the user's end) but would work.

**Comment by mcrossman** [comment]
It works when I build a new cookie with the path included like this:

```rust
res.del_cookie(&Cookie::build("subscriptions", "").path("/").finish());
```

But when I exclude the path, it doesn't get deleted. I'm guessing that since we're in `/r/sub/unsubscribe` the default response cookie is not modifying cookies at the root path.

Returning a cookie with no value is how it gets deleted. That's what I see in the response cookies when the settings page tries to do it.

**Comment by spikecodes** [comment]
Yeah, the way cookies get deleted is when you set the "expire" time to a past date or when the Max-Age is reached (`.del_cookie` sets the Max-Age to 0). You're right about the path. It seems that the `del_cookie` method seems to not specify one.

**Comment by spikecodes** [comment]
Could 
```rust
if sub_list.is_empty() {
	sub_list = Vec::new();
	sub_list.push(sub_name);
} else if !sub_list.contains(&sub_name) {
	sub_list.push(sub_name);
	sub_list.sort();
}
```
become
```rust
sub_list.push(sub_name);
sub_list.sort();
}
```
? Because when a vector `is_empty()`, it's value is the same as `Vec::new()`.

**Comment by mcrossman** [comment]
Yep, it can. Thanks.

**Comment by spikecodes** [comment]
The default homepage is now a subscription feed! (or `r/popular` if there you aren't subscribed to any)
image

**Comment by spikecodes** [comment]
It would nice to have a "Subscribe" button above the sort box when viewing multireddits (like `r/rust+privacy`) to allow people to subscribe to a multireddit of their Reddit subscriptions. This would make it easier for people to migrate from Reddit to Libreddit.

**Comment by mcrossman** [comment]
Done my testing, too.

Looks good to merge.

**Comment by spikecodes** [comment]
Thank you for this useful PR!

**Pull request merged**
