### PR TITLE
Added Dracula/Nord theme

### PR DESCRIPTION
**Pull request by Henryws**

### CODE REVIEW

**Comment by spikecodes** [comment]
Thank you for opening this PR! I love the Dracula theme you have added. :)

The one concern I have is distinguishing between the `--green` and `--accent`: the green is meant to stand out from the accent as it denotes stickied posts/comments and moderators. Perhaps the accent could be the purple or pink from Dracula's color palette?

**Comment by Henryws** [comment]
@spikecodes Done and added Nord theme per some ones request

**Comment by TheCultLeader666** [comment]
I would suggest changing the text color values from white to #f8f8f2 (Dracula), and #ECEFF4 (Nord)

**Comment by Henryws** [comment]
Any reason?

**Comment by TheCultLeader666** [comment]
Those are the official foreground colors for each theme

**Comment by Henryws** [comment]
Done

**Review by spikecodes — APPROVED** [review]
Looks great!

**Comment by spikecodes** [comment]
Thank you! Merged :)

**Pull request merged**
