### PR TITLE
Added heroku.yml

### PR DESCRIPTION
**Pull request by dacousb**

### CODE REVIEW

**Comment by spikecodes** [comment]
Are you able to provide a brief description as to what this pull request would do? Also, was there a specific reason for setting all the default settings to `false` in `app.json`?

**Comment by dacousb** [comment]
- This small change will make deploying to Heroku much easier (https://devcenter.heroku.com/articles/heroku-button).
- The options are not set to false by default, but I have marked them as not required.

**Comment by dacousb** [comment]
There seems to be some problems with port bindings in Heroku, I am investigating the problem. One solution would be to have the port work as follows (thing that should work with Heroku):
```rust
let port = env::var("PORT")
        .unwrap_or_else(|_| "8080".to_string())
        .parse()
        .expect("PORT is not a number");
```
or similar (this can also be handy for other platforms).

**Comment by dacousb** [comment]
I fixed the port issue, now it works perfectly in Heroku (I tested it).

**Comment by spikecodes** [comment]
Awesome, thanks for this pull request!

**Pull request merged**
