### PR TITLE
Add controversial sort order

### LINKED ISSUE #29: Support sort by controversial

### PR DESCRIPTION
**Pull request by moosingin3space**
Fixes #29.

### CODE REVIEW

**Comment by spikecodes** [comment]
Thank you for this PR. Are you able to turn on "allow editing by maintainers" so I can fix one thing?

**Comment by moosingin3space** [comment]
I submitted the PR with Allow edits checked.

**Comment by spikecodes** [comment]
For some reason, I am not able to submit a commit from GitHub Codespaces:
> git -c http.userAgent=git/2.29.2 (#32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020 5.4.0-1031-azure; linux x64) vscode/1.53.0-insider (Visual Studio Code - Insiders) push moosingin3space pr/moosingin3space/30:master
remote: Permission to moosingin3space/libreddit.git denied to spikecodes.
fatal: unable to access 'https://github.com/moosingin3space/libreddit/': The requested URL returned error: 403

**Comment by moosingin3space** [comment]
Huh, perhaps I need to add you as a collaborator to my fork.

**Comment by moosingin3space** [comment]
Sent you an invite to my fork. Hope that clears it up.

**Comment by spikecodes** [comment]
Thank you, the commit worked sucessfully.

**Pull request merged**
