### PR TITLE
WIP: Various subreddit & post fixes

### LINKED ISSUE #133: Bug Report | For r/random, name of sidebar's subreddit is different than that of posts
**Describe the bug**
It seems as if Libreddit is randomizing both the sidebar and posts so that the sidebar's subreddit is one thing, while the posts' subreddit is another.

**To reproduce**
1. Go to r/random
2. Check if sidebar's subreddit is same as posts' subreddit
imageedit_1_3075327271

**Expected behavior**
Both should match.

**Additional context**
This also applies to r/randnsfw.

### LINKED ISSUE #173: Bug Report | Large sub_icon is loaded instead of small one
1. https://libredd.it/r/yandere_simulator/
2. 2654*2654 sub_icon takes its time to load, and is massively scaled down: https://libredd.it/style/t5_37nnf/styles/communityIcon_q7ii7cfyqgc51.png

**Expected**
More appropriate image size, like reddit's 256*256: https://www.reddit.com/r/yandere_simulator/ -  https://styles.redditmedia.com/t5_37nnf/styles/communityIcon_q7ii7cfyqgc51.png?width=256&s=83f6ec427f42929cd5f829bcf537867f8b61b7d0

### PR DESCRIPTION
**Pull request by curlpipe**
Closes #133 and closes #173 

133:
  - [X] Fix random subreddit sidebar mismatch

173:
- [x] Load small sub icon instead of large one for performance gain

### CODE REVIEW

**Comment by spikecodes** [comment]
I really appreciate all these contributions! I've responded to #218 as I don't feel this is a Libreddit issue so I don't think the fix here will be necessary.

**Comment by curlpipe** [comment]
I shall revert those changes in that case.

**Comment by curlpipe** [comment]
Reverted :)

**Comment by spikecodes** [comment]
Fantastic job, thank you again!

**Pull request merged**
