### PR TITLE
Added 2 new themes: violet & gold

### PR DESCRIPTION
**Pull request by curlpipe**
So I added 2 new themes to libreddit.

image
image

### CODE REVIEW

**Comment by TheCultLeader666** [comment]
I love the influx of new themes

**Comment by spikecodes** [comment]
I love these themes, especially the gold! Is it possible to add more contrast to the violet theme? This would improve accessibility and legibility.

**Comment by curlpipe** [comment]
Made adjustment to contrast and brightness

image

**Comment by curlpipe** [comment]
Adjusted the accent colour.

**Comment by spikecodes** [comment]
Looks great, thanks!

**Pull request merged**
